name: Build & Run

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  basics:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./basics

    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 빌드
        run: make

      - name: hello 실행 (1)
        run: ./hello 1

      - name: hello 실행 (2)
        run: ./hello 3

      - name: hello 실행 (3)
        run: ./hello 10

      - name: hello_id 실행 (1)
        run: ./hello_id 1

      - name: hello_id 실행 (2)
        run: ./hello_id 3

      - name: hello_id 실행 (3)
        run: ./hello_id 8

      - name: hello_id 실행 (4)
        run: ./hello_id 15 | sort -V

      - name: hello_id 실행 (5)
        run: ./hello_id 100 | wc -l

      - name: hello_parity 실행 (1)
        run: ./hello_parity 3

      - name: hello_parity 실행 (2)
        run: ./hello_parity 8

      - name: hello_parity 실행 (3)
        run: ./hello_parity 50 | grep even | wc -l

  sums:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sums

    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 빌드
        run: make

      - name: split 실행 (1)
        run: ./split 100 1

      - name: split 실행 (2)
        run: ./split 100 2

      - name: split 실행 (3)
        run: ./split 100 3

      - name: split 실행 (4)
        run: ./split 100 8

      - name: split 실행 (5)
        run: time ./split 1000000000 1

      - name: split 실행 (6)
        run: time ./split 1000000000 2

      - name: split 실행 (7)
        run: time ./split 1000000000 4

      - name: split 실행 (8)
        run: time ./split 1000000000 8

      - name: split 실행 (9)
        run: time ./split 1000000000 16

      - name: dnc 실행 (1)
        run: ./dnc 100 1

      - name: dnc 실행 (2)
        run: ./dnc 100 2

      - name: dnc 실행 (3)
        run: ./dnc 100 3

      - name: dnc 실행 (4)
        run: ./dnc 100 8

      - name: dnc 실행 (5)
        run: time ./dnc 1000000000 1

      - name: dnc 실행 (6)
        run: time ./dnc 1000000000 2

      - name: dnc 실행 (7)
        run: time ./dnc 1000000000 4

      - name: dnc 실행 (8)
        run: time ./dnc 1000000000 8

      - name: dnc 실행 (9)
        run: time ./dnc 1000000000 16
