name: Build & Run

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  basics:
    runs-on: ubuntu-latest

    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 빌드
        run: |
          cd basics
          make

      - name: hello 실행 (1)
        run: |
          cd basics
          ./hello 1

      - name: hello 실행 (2)
        run: |
          cd basics
          ./hello 3

      - name: hello 실행 (3)
        run: |
          cd basics
          ./hello 10

      - name: hello_id 실행 (1)
        run: |
          cd basics
          ./hello_id 1

      - name: hello_id 실행 (2)
        run: |
          cd basics
          ./hello_id 3

      - name: hello_id 실행 (3)
        run: |
          cd basics
          ./hello_id 8

      - name: hello_id 실행 (4)
        run: |
          cd basics
          ./hello_id 15 | sort -V

      - name: hello_id 실행 (5)
        run: |
          cd basics
          ./hello_id 100 | wc -l

      - name: hello_parity 실행 (1)
        run: |
          cd basics
          ./hello_parity 3

      - name: hello_parity 실행 (2)
        run: |
          cd basics
          ./hello_parity 8

      - name: hello_parity 실행 (3)
        run: |
          cd basics
          ./hello_parity 50 | grep even | wc -l

  sums:
    runs-on: ubuntu-latest

    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 빌드
        run: |
          cd sums
          make

      - name: split 실행 (1)
        run: |
          cd sums
          ./split 100 1

      - name: split 실행 (2)
        run: |
          cd sums
          ./split 100 2

      - name: split 실행 (3)
        run: |
          cd sums
          ./split 100 3

      - name: split 실행 (4)
        run: |
          cd sums
          ./split 100 8

      - name: split 실행 (5)
        run: |
          cd sums
          time ./split 1000000000 1

      - name: split 실행 (6)
        run: |
          cd sums
          time ./split 1000000000 2

      - name: split 실행 (7)
        run: |
          cd sums
          time ./split 1000000000 4

      - name: split 실행 (8)
        run: |
          cd sums
          time ./split 1000000000 8

      - name: split 실행 (9)
        run: |
          cd sums
          time ./split 1000000000 16
